<?php
namespace Flexi\CourseEnrolement;
use Illuminate\Support\ServiceProvider;

class CourseEnrolementServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->loadRoutesFrom(__DIR__.'/routes/web.php');
        $this->loadViewsFrom(__DIR__.'/views', 'Flexi\CourseEnrolement');
        $this->loadMigrationsFrom(__DIR__.'/database/migrations');
        $this->mergeConfigFrom(__DIR__.'/config/course_enrolement.php', 'Flexi\CourseEnrolement');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}